server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 30000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      -
        id: elastic-query-service-1
        host: localhost
        port: 8183
#      -
#        id: elastic-query-service-2
#        host: localhost
#        port: 8185

  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  oauth2:
    client:
      registration:
        keycloak:
          client-id: 'elastic-query-web-client'
          client-secret: '3288bbed-fe78-451e-98ae-29f4f86c1102'
          authorization-grant-type: authorization_code
          redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          scope: openid
      provider:
        keycloak:
          issuerUri: http://localhost:8081/auth/realms/microservices-realm

security:
  logout-success-url: http://localhost:8184/elastic-query-web-client/login/oauth2/code/keycloak
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}d8e481ab540ad71f2a4231dc402350dec21892cb91799c59b8dba0476cc6e321'
  roles: USER