server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'

spring:
  thymeleaf:
    cache: false

user-config:
  username: test
  password: '{cipher}d8e481ab540ad71f2a4231dc402350dec21892cb91799c59b8dba0476cc6e321'
  roles: USER